name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - uses: brokeyourbike/go-mockery-action@v0.1
      with:
        mockery-version: '2.14.0'
    - run: mockery --all --keeptree
    - run: cp config.dist.toml config.toml
    - run: go build -v ./...
    - run: go test -race -covermode=atomic -coverprofile=coverage.out -v ./...

    - uses: paambaati/codeclimate-action@v3.0.0
      continue-on-error: true
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TOKEN }}
      with:
        coverageCommand: ''
        prefix: 'github.com/brokeyourbike/jsonarray'
        coverageLocations: ./coverage.out:gocov

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: brokeyourbike/go-mockery-action@v0.1
        with:
          mockery-version: '2.14.0'
      - run: mockery --all --keeptree
      - uses: dominikh/staticcheck-action@v1
        with:
          version: "2022.1"
          install-go: false