name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: 1.19
    - run: GORM_DIALECT=sqlite go build --tags "json1" -v ./...
    - run: GORM_DIALECT=sqlite go test --tags "json1" -race -covermode=atomic -coverprofile=coverage.out -v ./...

    - uses: paambaati/codeclimate-action@v3.0.0
      continue-on-error: true
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TOKEN }}
      with:
        coverageCommand: ''
        prefix: 'github.com/brokeyourbike/jsonarray'
        coverageLocations: ./coverage.out:gocov